// Code generated by Netspective IGS. DO NOT EDIT.

export interface Profile {
  readonly firstName?: string; // Any arbitrary text (guessed from 'First Name' row 1)
  readonly lastName?: string; // Any arbitrary text (guessed from 'Last Name' row 1)
  readonly maidenName?: unknown; // Unknown property (guessed from 'Maiden Name' row 1, retries: 1)
  readonly address?: unknown; // Unknown property (guessed from 'Address' row 1, retries: 1)
  readonly birthDate?: unknown; // Unknown property (guessed from 'Birth Date' row 1, retries: 1)
  readonly headline?: string; // Any arbitrary text (guessed from 'Headline' row 1)
  readonly summary?: string; // Any arbitrary text (guessed from 'Summary' row 1)
  readonly industry?: string; // Any arbitrary text (guessed from 'Industry' row 1)
  readonly zipCode?: number; // Any text that can be converted to an integer value (guessed from 'Zip Code' row 1)
  readonly geoLocation?: string; // Any arbitrary text (guessed from 'Geo Location' row 1)
  readonly twitterHandles?: string; // Any arbitrary text (guessed from 'Twitter Handles' row 1)
  readonly websites?: string; // Any arbitrary text (guessed from 'Websites' row 1)
  readonly instantMessengers?: string; // Any arbitrary text (guessed from 'Instant Messengers' row 1)
}

export interface Education {
  readonly schoolName?: string; // Any arbitrary text (guessed from 'School Name' row 1)
  readonly startDate?: number; // Any text that can be converted to an integer value (guessed from 'Start Date' row 1)
  readonly endDate?: number; // Any text that can be converted to an integer value (guessed from 'End Date' row 1)
  readonly notes?: unknown; // Unknown property (guessed from 'Notes' row 1, retries: 4)
  readonly degreeName?: string; // Any arbitrary text (guessed from 'Degree Name' row 1)
  readonly activities?: unknown; // Unknown property (guessed from 'Activities' row 1, retries: 4)
}

export interface Events {
  readonly eventName?: string; // Any arbitrary text (guessed from 'Event Name' row 1)
  readonly eventTime?: string; // Any arbitrary text (guessed from 'Event Time' row 1)
  readonly status?: string; // Any arbitrary text (guessed from 'Status' row 1)
  readonly externalUrl?: string; // Any text that matches RegExp /^https?:\/\/((([a-z]|[0-9]|[-._~])|%[0-9a-f][0-9a-f]|[!$&'()*+,;=]|:)*@)?(.... (guessed from 'External Url' row 1)
}

export interface Patents {
  readonly title?: string; // Any arbitrary text (guessed from 'Title' row 1)
  readonly description?: string; // Any arbitrary text (guessed from 'Description' row 1)
  readonly url?: string; // Any text that matches RegExp /^http?:\/\/((([a-z]|[0-9]|[-._~])|%[0-9a-f][0-9a-f]|[!$&'()*+,;=]|:)*@)?(\.... (guessed from 'Url' row 2)
  readonly issuer?: string; // Any arbitrary text (guessed from 'Issuer' row 1)
  readonly applicationNumber?: string; // Any arbitrary text (guessed from 'Application Number' row 2)
  readonly filedOn?: string; // Any arbitrary text (guessed from 'Filed On' row 2)
  readonly issuedOn?: string; // Any arbitrary text (guessed from 'Issued On' row 1)
  readonly patentNumber?: number; // Any text that can be converted to an integer value (guessed from 'Patent Number' row 1)
}

export interface Positions {
  readonly companyName?: string; // Any arbitrary text (guessed from 'Company Name' row 1)
  readonly title?: string; // Any arbitrary text (guessed from 'Title' row 1)
  readonly description?: string; // Any arbitrary text (guessed from 'Description' row 1)
  readonly location?: string; // Any arbitrary text (guessed from 'Location' row 1)
  readonly startedOn?: string; // Any arbitrary text (guessed from 'Started On' row 1)
  readonly finishedOn?: string; // Any arbitrary text (guessed from 'Finished On' row 10)
}

export interface Projects {
  readonly title?: string; // Any arbitrary text (guessed from 'Title' row 1)
  readonly description?: string; // Any arbitrary text (guessed from 'Description' row 1)
  readonly url?: string; // Any text that matches RegExp /^http?:\/\/((([a-z]|[0-9]|[-._~])|%[0-9a-f][0-9a-f]|[!$&'()*+,;=]|:)*@)?(\.... (guessed from 'Url' row 1)
  readonly startedOn?: number; // Any text that can be converted to an integer value (guessed from 'Started On' row 1)
  readonly finishedOn?: string; // Any arbitrary text (guessed from 'Finished On' row 5)
}

export interface Publications {
  readonly name?: string; // Any arbitrary text (guessed from 'Name' row 1)
  readonly publishedOn?: string; // Any arbitrary text (guessed from 'Published On' row 1)
  readonly description?: string; // Any arbitrary text (guessed from 'Description' row 1)
  readonly publisher?: string; // Any arbitrary text (guessed from 'Publisher' row 1)
  readonly url?: string; // Any text that matches RegExp /^https?:\/\/((([a-z]|[0-9]|[-._~])|%[0-9a-f][0-9a-f]|[!$&'()*+,;=]|:)*@)?(.... (guessed from 'Url' row 1)
}

export interface RecommendationsGiven {
  readonly firstName?: string; // Any arbitrary text (guessed from 'First Name' row 1)
  readonly lastName?: string; // Any arbitrary text (guessed from 'Last Name' row 1)
  readonly company?: string; // Any arbitrary text (guessed from 'Company' row 1)
  readonly jobTitle?: string; // Any arbitrary text (guessed from 'Job Title' row 1)
  readonly text?: string; // Any arbitrary text (guessed from 'Text' row 1)
  readonly creationDate?: string; // Any arbitrary text (guessed from 'Creation Date' row 1)
  readonly status?: unknown; // Unknown property (guessed from 'Status' row 1, retries: 50)
}

export interface RecommendationsReceived {
  readonly firstName?: string; // Any arbitrary text (guessed from 'First Name' row 1)
  readonly lastName?: string; // Any arbitrary text (guessed from 'Last Name' row 1)
  readonly company?: string; // Any arbitrary text (guessed from 'Company' row 1)
  readonly jobTitle?: string; // Any arbitrary text (guessed from 'Job Title' row 1)
  readonly text?: string; // Any arbitrary text (guessed from 'Text' row 1)
  readonly creationDate?: string; // Any arbitrary text (guessed from 'Creation Date' row 1)
  readonly status?: string; // Any arbitrary text (guessed from 'Status' row 1)
}

export interface Skills {
  readonly name?: string; // Any arbitrary text (guessed from 'Name' row 1)
}

export interface LinkedInArchive {
  readonly profile: Profile;
  readonly education: Education[];
  readonly events: Events[];
  readonly patents: Patents[];
  readonly positions: Positions[];
  readonly projects: Projects[];
  readonly publications: Publications[];
  readonly recommendationsGiven: RecommendationsGiven[];
  readonly recommendationsReceived: RecommendationsReceived[];
  readonly skills: Skills[];
}

export const linkedInArchive: LinkedInArchive = {
  profile: {
    firstName: "Shahid",
    lastName: "Shah",
    headline:
      "Shahid Shah is a GovTech & Health IT Entrepreneur, Keynote Speaker, CTO targeting AI/ML/Blockchain/Conversational UX",
    summary:
      "I’m a company builder. I love making products that require complex engineering skills but need to be easy to deploy and use. My passion is innovation that improves people’s lives in measurable ways. My experience has been in regulated, security-conscious, safety-critical industries such as Med Devices, Digital Health (health IT), and Gov 2.0 because they’re usually creating the most demanding products and services.  I'm a C-suite native that can easily blend in with technical and engineering teams that need to deliver revenue-generating solutions to the marketplace. I have years of leadership experience that have helped transform product teams from marginal to high performance. My strategic foresight, thinking, and execution capabilities help companies understand their technology strategy weaknesses and help renovate their architecture and engineering groups into business focused technology units that can deliver high margin, high revenue, and high value solutions.   My communications skills are top notch. I can easily explain complex technical topics to non-technical colleagues in board rooms as well as stand up and speak about industry trends or deep technology topics at public and private events in front of thousands of people. I’ve spoken at dozens of conferences and many of my presentations are publicly available at www.SpeakerDeck.com/shah. I love sharing my skills and knowledge as both a social media influencer (author, blogger) and a private consensus-builder (when leading projects).  My software/hardware engineering and cybersecurity body of knowledge is up to date because I roll up my sleeves to create code when appropriate & dive into system architecture and design when required. I also conduct technology due diligence exercises for corporate acquisition or product integration requirements. My deep engineering and communications skills are both on display at my blog www.HealthcareGuy.com.  See http://ShahidShah.com for my interactive bio.",
    industry: "Computer Software",
    zipCode: 20904,
    geoLocation: "Silver Spring, Maryland, United States",
    twitterHandles: "[ShahidNShah,netspectivehc,netspective,netspectivegov]",
    websites:
      "[PERSONAL:http://www.ShahidShah.com,BLOG:http://www.HealthcareGuy.com,OTHER:http://shahidshah.brandyourself.com]",
    instantMessengers: "[SKYPE:ShahidNShah]"
  },
  education: [
    {
      schoolName: "University of Maryland University College",
      startDate: 1996,
      endDate: 1998,
      degreeName: "Master of Science (M.Sc.)"
    },
    {
      schoolName: "Pennsylvania State University-Penn State Harrisburg",
      startDate: 1988,
      endDate: 1990,
      degreeName: "Bachelor of Science (B.Sc.)"
    },
    {
      schoolName: "Pennsylvania State University-Penn State York",
      startDate: 1987,
      endDate: 1988
    },
    { schoolName: "University of Houston", startDate: 1986, endDate: 1987 }
  ],
  events: [
    {
      eventName: "IIoT World Days ",
      eventTime: "Jun 30, 2020 12:30 PM - Jul 02, 2020 12:00 AM",
      status: "ATTENDING",
      externalUrl:
        "https://www.eventbrite.com/e/iiot-world-days-tickets-106478889224"
    },
    {
      eventName: "6th Annual Veterans Awards",
      eventTime: "Nov 11, 2020 11:00 PM - Nov 12, 2020 04:00 AM",
      status: "ATTENDING",
      externalUrl: "https://www.ausvfoundation.org/6th-vettys"
    }
  ],
  patents: [
    {
      title:
        "Computer system for performing reusable software application development from a set of declarative executable specifications",
      description:
        "In May 2006 I was awarded this patent for reusable software. It describes a method I invented for performing architecture, design, and implementation of sophisticated business software using a specifications language.",
      issuer: "us",
      issuedOn: "May 2006",
      patentNumber: 7039898
    },
    {
      title: "Social Authentication for Accessing Health Records",
      description:
        "A system for facilitating access to a Social Heath Record Database (SHRDB) through a social networking platform over a communications network. The system includes an information management platform including one or more database server and one or more social network server configured to implement information storage and retrieval functions within the SHRDB. The system further includes the SHRDB communicatively coupled to the information management platform. The system further includes a social networking engine communicatively coupled to the SHRDB through the social network server to allow interfacing of the SHRDB with the social networking service/platform. The system further includes a programmatic web interface configured as a single sign-on scheme to allow access of one or more repositories of the SHRDB.",
      url: "http://www.google.com/patents/US20130204641",
      issuer: "us",
      applicationNumber: "US20130204641",
      filedOn: "Jan 31, 2013"
    },
    {
      title: "Social health care record system and method",
      description:
        "A system for facilitating multi-faceted communication over a network. The system includes a plurality of healthcare related entities connected with a communications network. Each of the plurality of healthcare related entities serve as a source of medical records. The system includes a social health care record data bank (SHRDB) accessible by each of the plurality of entities based on rules and preferences of the entities upon authorization by the SHRDB. The SHRDB includes a processing component capable of executing stored instructions to process the medical records of the entities over the communications network. The SHRDB further includes a repository to store the medical records of the plurality of entities. The system includes a multi-faceted social health care component communicatively coupled to the SHRDB and adapted to be accessible by each of the plurality of entities.",
      url: "http://www.google.com/patents/US20130197939",
      issuer: "us",
      applicationNumber: "US20130197939",
      filedOn: "Jan 14, 2013",
      patentNumber: NaN
    },
    {
      title:
        "System and method for managing devices and data in a medical environment",
      description:
        "A system and method for facilitating coordinated functioning of medical devices over a network. The system includes a communication circuit to receive an input indicative of an action to be performed by a first medical device from a processing unit coupled to a social health record data bank. The communication circuit is configured to send an instruction to the first medical device to initiate the action by the first medical device in association with information of a patient associated with the first medical device stored in and retrieved from the social health record data bank. The system further includes a control circuit configured to monitor the action performed by the first medical device and instruct the first medical device to pause performing the action for a defined period of time based on an instruction from the processing unit indicative of an action to be performed by a second medical device.",
      url: "http://www.google.com/patents/US20130204145",
      issuer: "us",
      applicationNumber: "US20130204145",
      filedOn: "Jan 31, 2013"
    },
    {
      title:
        "System and method for creating metadata-based natural language processing capabilities",
      description:
        "A system and method for managing data in a healthcare environment can include a content based router, and a healthcare record bank. The content based router can be configured to collect the data from a clinical data provider and convert the data in a format in accordance with a defined standard. The healthcare record bank can include or be coupled to a data repository. The healthcare record bank can be configured to be coupled to the clinical data provider through the content based router over a communication network. The healthcare record bank can be configured to store the data received from the clinical data provider and can be accessible or searchable from within or outside the healthcare record bank. The healthcare record bank can be coupled to or include a data logging unit configured to maintain metadata associated with the clinical data and configured to facilitate natural language processing capabilities.",
      issuer: "us",
      applicationNumber: "13/457,782",
      filedOn: "Apr 27, 2012"
    },
    {
      title:
        "System and Method for Providing Clinical Views or Recommendations",
      description: "Physician-based engine for clinical recommendations.",
      url:
        "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PG01&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.html&r=1&f=G&l=50&s1=%2220130297323%22.PGNR.&OS=DN/20130297323&RS=DN/20130297323",
      issuer: "us",
      applicationNumber: "20130297323",
      filedOn: "Nov 7, 2013"
    },
    {
      title: "System and Method for Collaborative Patient Engagement",
      url:
        "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO1&Sect2=HITOFF&d=PG01&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.html&r=1&f=G&l=50&s1=%2220130304508%22.PGNR.&OS=DN/20130304508&RS=DN/20130304508",
      issuer: "us",
      applicationNumber: "20130304508",
      filedOn: "May 14, 2012"
    },
    {
      title: "Consumer Self-authorization for Electronic Records",
      issuer: "us",
      applicationNumber: "13/607,997",
      filedOn: "Sep 10, 2012"
    }
  ],
  positions: [
    {
      companyName: "Citus Health",
      title: "Cofounder, Chairman of the Board",
      description:
        "Citus Health is bringing breakthrough technology to home healthcare. It is our mission to modernize an industry saddled with outdated processes, and give patients reliable, convenient, user-friendly medical technology while reducing the provider's bottom line.",
      location: "Greater New York City Area",
      startedOn: "Jan 2016"
    },
    {
      companyName: "Netspective Media",
      title: "Publisher",
      description:
        "I founded and run one the web's oldest healthcare IT blogs and media properties where the daily conversations of dozens of premium health technology bloggers is curated into one convenient site.",
      startedOn: "2005"
    },
    {
      companyName: "Netspective Communications",
      title: "Founder",
      description:
        "Netspective is a provider of technology strategy, sales and marcomm expertise, as well as architecture and engineering solutions to government agencies/contractors, systems integrators, health IT vendors, med device manufacturers, and life sciences customers.   From ideation to execution, we extend your enterprise in these ways:  * Leadership Augmentation via Fractional CTO Services, Roadmapping & Planning, plus Mentoring & Coaching * Extend R&D teams through Tech Strategy Development, Outsourced Coding & Engineering, Outsourced QA & Validation, and Regulatory Strategy development * Extend Product Marketing teams with Ideation, Requirements & Prototyping, Product Management, and Market Validation * Extend Sales groups via Market Education, Sales Strategy Development, Social Sales & Collaboration, and Lead Gen Assistance  All of our capabilities are centered around deep technical talent and senior executive experience that can applied to help create high margin, high revenue, and high value solutions.",
      location: "Washington D.C. Metro Area",
      startedOn: "Feb 2001"
    },
    {
      companyName: "Hoy Health",
      title: "Member, Strategic Board of Advisors",
      description:
        "Providing technological and regulatory advice to this innovative company as it establishes a “Virtual Integrated Delivery Network” destined to be become a leader in effective, low cost and personalized healthcare delivery and support for underserved medical communities.",
      startedOn: "Mar 2016"
    },
    {
      companyName: "Larta Institute",
      title: "Health Sciences and Technology Advisor",
      description:
        "Advising R&D startups through commercialization assistance programs (SBIR/STTR) promoting movement of ideas and technologies through a support network and onto new markets sustained by strategic introductions, follow-on capital, acquisitions, and job creation.",
      startedOn: "2007"
    },
    {
      companyName: "Ryohee",
      title: "Investor, Member of the Board of Directors",
      location: "Boca Raton, Florida Area",
      startedOn: "Jul 2012"
    },
    { companyName: "Teleport App", title: "Investor", startedOn: "Mar 2016" },
    {
      companyName: "Hybrent",
      title: "Member of the Board of Directors",
      startedOn: "Sep 2014"
    },
    {
      companyName: "Goomzee",
      title: "Investor",
      description: "Angel investor in this innovative real estate tech firm.",
      startedOn: "2008"
    },
    {
      companyName: "twazer",
      title: "Investor, Member of the Board of Directors",
      location: "Greater Los Angeles Area",
      startedOn: "May 2015",
      finishedOn: "Dec 2019"
    },
    {
      companyName: "Poliwogg",
      title: "Investor",
      description:
        "Poliwogg connects private sector investors with pre-vetted innovative healthcare investment opportunities. Instead of a shotgun approach, Poliwogg encourages precision investing for the modern crowd equity era, with a focus on specific conditions, diagnostics, and threapeutics.",
      startedOn: "Apr 2015",
      finishedOn: "Dec 2019"
    },
    {
      companyName: "America's Health Insurance Plans (AHIP)",
      title:
        "Entrepreneur in Residence and Strategic Adviser for the Innovation Lab",
      description:
        "Served as Strategic Adviser and Entrepreneur-in-Residence (EIR) for AHIP's Innovation Lab (\"AHIP IL\"). AHIP's IL is a 26,000 sq ft facility located at Chicago's West Loop which is an invaluable resource for member health plans to use for ideation and implementation of innovative initiatives. Shahid helps the IL run Solution Working Groups for AHIP's individual payers and helps incorporate the broader healthcare ecosystem of providers, manufacturers, MedTech, and the Lab's trusted and crucial Inaugural Partners.  AHIP IL believes that the major problems in healthcare now requires significant collaboration by and between health plans, health systems, innovative companies, pharmaceutical manufacturers, retail pharmacies, and most importantly patients.",
      location: "Washington D.C. Metro Area",
      startedOn: "Jan 2015",
      finishedOn: "Mar 2018"
    },
    {
      companyName: "Caristix",
      title: "Member of the Board of Directors",
      description:
        "Interoperability is now a major topic in healthcare circles and Caristix is in the business of doing the heavy lifting of enabling EHRs and other systems to connect with each other.",
      location: "Washington D.C. Metro Area",
      startedOn: "Feb 2015",
      finishedOn: "Dec 2017"
    },
    {
      companyName: "OSEHRA (Open Source Electronic Health Record Alliance)",
      title: "Chairman, Strategic Board of Advisors",
      description:
        "Advising new DoD and VA founded organization on formation of open innovations and open source software for healthcare industry.",
      location: "Washington D.C. Metro Area",
      startedOn: "May 2012",
      finishedOn: "Jan 2016"
    },
    {
      companyName: "PrescribeWell",
      title: "Investor",
      description:
        "Co-founded this innovative startup focused on helping health systems create new profit centers in their physician practices. We create digital health tools and platforms that use cutting edge science and clinical expertise to help physicians work with patients to lose weight and improve overall wellness.",
      location: "Greater Philadelphia Area",
      startedOn: "2013",
      finishedOn: "2016"
    },
    {
      companyName: "simplifyMD",
      title: "co-Founder and CTO",
      description:
        "Co-founded and served as CTO of this digital healthcare startup that created a Meaningful Use Certified Electronic Health Records (EHR) solution for small to medium sized medical offices. simplifyMD merged with Azalea Health in 2014.",
      startedOn: "May 2007",
      finishedOn: "Dec 2013"
    },
    {
      companyName: "Comsys",
      title: "SVP Healthcare Technology Strategy",
      description:
        "Helped develop technology strategy for a new healthcare products and services division of COMSYS after the purchase of Physia intellectual property assets.",
      startedOn: "Sep 2002",
      finishedOn: "May 2004"
    },
    {
      companyName: "Physia Corporation",
      title: "co-Founder and CTO",
      description:
        "Co-founded and served as CTO of one of the world's first cloud-based EHR platforms. Sold to COMSYS in 2001.",
      location: "Houston, Texas Area",
      startedOn: "Mar 1999",
      finishedOn: "Jan 2001"
    },
    {
      companyName: "Northrop Grumman (formerly TRW)",
      title: "Senior System Architect and Lead Software Engineer",
      description:
        "As a contractor for Northrop Grumman, led the technical team responsible for the development of the American Red Cross National Biomedical Computer Systems (NBCS) Releases 1.0 and 1.1. The Red Cross NBCS system is the largest automated blood collection and distribution system in the world, responsible for delivery of over 50% of the blood supply in the United States. NBCS is deployed over a heterogeneous, distributed client/server environment with IBM AIX and Microsoft NT servers, and host-based and Microsoft Windows clients. Responsible for team leadership, software specifications, software development (ANSI C/C++ and UNIX Shell scripts), design reviews, code reviews, code management, scheduling, interviewing, and hiring.  Led the technical team responsible for the development and deployment of several client/server components of NBCS Release 1.1. These include medium-size applications that perform centralized reporting services (using Web/CGI applications, Crystal Reports and Delphi) and telerecruiting (using the web).",
      startedOn: "Mar 1995",
      finishedOn: "Feb 1999"
    },
    {
      companyName: "US Navy",
      title: "Computer Scientist",
      description:
        "Worked as civilian researcher at the Naval Surface Warfare Center in White Oak, MD (which later moved to Dahlgren, VA). Developed C++ software on a team project. C++ application was for ground-based UNIX workstations to perform simulation and testing of ship-based computer software and hardware.   Developed MS-Windows and OSF Motif software tools in C++ and Borland Pascal to perform reverse engineering and analysis of over fifty megabytes of code and data used on AEGIS-class cruisers and destroyers. Required complete database analysis and design specifications, communication with end-users, downsizing to client/server paradigm, programming the software, and documentation.  Enhanced programs in FORTRAN and C to support underwater (submarine) vessel simulation projects.  Worked on MARS project for support of low-level networking  to enhance war games and hi-res 3D graphics for fleet combat simulation programs.  Wrote and had published technical reports and highlights. Served as chairman of the OOP subcommittee of the Navy Next Generation Computer Resources group.",
      startedOn: "Jul 1990",
      finishedOn: "Dec 1994"
    }
  ],
  projects: [
    {
      title: "The Healthcare IT Guy Blog",
      description:
        " I've been blogging about healthcare technology, solutions, and policy issues for many years.",
      url: "http://www.healthcareguy.com",
      startedOn: 2005
    },
    {
      title: "BFELoB MAX Federal Community Architect",
      description:
        "Serve as Consulting Chief Architect (Contractor) of this Federal Government collaboration system.",
      startedOn: NaN
    },
    {
      title: "Digital Health & Medical Device Equity Research",
      description:
        "Consult with companies such as FBR, Lazard Capital Markets, and DeMatteo Monness to help them help their clients better understand the complex world of health IT and medical device technology that aids their investment decision making process.",
      startedOn: NaN
    },
    {
      title: "Global Genomics Group CTO",
      description:
        "Enterprise IT strategy, bioinformatics strategy, and information management implementation for this research-oriented, discovery-based, life sciences company. Responsible for data storage, data movement, bioinformatics and digital chemistry analysis pipelines, and data security.",
      url: "http://www.GlobalGenomicsGroup.com",
      startedOn: NaN
    },
    {
      title: "Poliwogg CTO",
      description:
        "Served as fractional CTO during formation of Poliwogg's initial technology platforms and products.",
      url: "http://www.poliwogg.com",
      startedOn: NaN,
      finishedOn: "May 2014"
    },
    {
      title:
        "Advisor, NIH/TATRC Commercialization Assistance Program run by Larta",
      description:
        "I helped advise over a dozen NIH and TATRC selected companies that were enrolled in the Commercialization Assistance Program (CAP). The program is administered by Larta on behalf of National Institutes of Health (NIH) and other government agencies.",
      startedOn: 2006,
      finishedOn: "2013"
    },
    {
      title: "Cardinal Health Clinical Technologies & Services (CTS) CTO",
      description:
        "Served at Chief Technology Officer (CTO) reporting to CTS Business Unit CEO; led technology strategy and hardware as well as software engineering teams for all medical devices/solutions including Alaris, Pyxis, and other product lines.",
      startedOn: 2006,
      finishedOn: "2007"
    },
    {
      title:
        "American Red Cross National Biomedical Computer System (NBCS) Architect",
      description:
        "Served as Consulting Chief Architect (Contractor) for Red Cross's MACS NBCS -- a large enterprise system that helps manage the nation's blood supply and regulated as a Class 3 medical device by the FDA.",
      startedOn: 2001,
      finishedOn: "2003"
    },
    {
      title: "HealthIMPACT Forum",
      description: 'The ultimate "No BS" Digital Health Conference series.',
      url: "http://purposeevents.com/",
      startedOn: NaN
    }
  ],
  publications: [
    {
      name:
        'Chapters 10 and 20 in "Risk Management, Liability Insurance, and Asset Protection Strategies for Doctors and Advisors: Best Practices from Leading Consultants and Certified Medical Planners"',
      publishedOn: "Dec 2015",
      description:
        'I wrote Chapter 10 "Understanding Medical Practice Cybersecurity Risks: Mitigations for the Digital Health Era" and Chapter 20 "How to Conduct a Health-Care Environment Electronic Risk Assessment: Mitigations for the Digital Health Era" in this compilation of content which explains to physicians and insurance professionals the background, theory, and practicalities of medical risk management, asset protection methods, and insurance planning.',
      publisher: "CRC Press, Taylor & Francis Group",
      url:
        "https://www.crcpress.com/Risk-Management-Liability-Insurance-and-Asset-Protection-Strategies-for/Marcinko-Hetico/9781498725989"
    },
    {
      name:
        'Chapter 13 "Interoperable EMRs - On Being the CIO of Your Practice" in "The Business of Medical Practice: Transformational Health 2.0 Skills for Doctors, Third Edition"',
      publishedOn: "2011",
      description:
        "I wrote Chapter 13 (pages 299 through 335) of the 3rd Edition of the book entitled 'The Business of Medical Practice: Transformational Health 2.0 Skills for Doctors'. My chapter deals with how medical and clinical specialists should make healthcare technology decisions, how to choose consultants, focus on the right areas of their practice to automate, how best to collaborate with patients online, preparing for mHealth, and how to demo and buy electronic health records solutions.",
      publisher: "Springer Publishing Company, New York",
      url: "http://www.BusinessofMedicalPractice.com"
    },
    {
      name: "Prepare your practice for an EMR",
      publishedOn: "Apr 1, 2011",
      description:
        "I prepared a basic checklist to help physicians prepare for the purchase of a large, expensive, electronic health records solution.",
      publisher: "Journal of Surgical Radiology",
      url:
        "http://www.surgisphere.com/SurgRad/Issues/Volume-2-April-2011/index.html"
    },
    {
      name: "Why MDs Dread EMRs",
      publishedOn: "Jul 1, 2010",
      description:
        "A column on why physicians haven't embraced electronic health records solutions even after decades of implementations.",
      publisher: "Journal of Surgical Radiology",
      url:
        "http://www.surgisphere.com/SurgRad/issues/volume-1/1-july-2010--pages-1-60/119-column-why-mds-dread-emrs.html"
    },
    {
      name: "How To Obtain Quality IT Help",
      publishedOn: "Oct 1, 2010",
      description:
        "Getting quality help from IT consultants is not easy -- this column describes how to make sure you're doing the right things when asking for help.",
      publisher: "Journal of Surgical Radiology",
      url:
        "http://www.surgisphere.com/SurgRad/issues/volume-1/1-october-2010-pages-61-122/144-column-how-to-obtain-quality-it-help.html"
    },
    {
      name: "Social Networking for Physicians",
      publishedOn: "Jan 1, 2011",
      description:
        "This columns is about how physicians can increase their personal credibility and establish a personal brand by using social networking tools and techniques. ",
      publisher: "Journal of Surgical Radiology",
      url:
        "http://www.surgisphere.com/SurgRad/issues/volume-2/1-january-2011-pages-1-112/150-column-social-networking.html"
    },
    {
      name: "Easing Into Healthcare Automation",
      publishedOn: "Feb 17, 2011",
      description:
        "Most healthcare providers shouldn't jump into complex systems like EHRs without a ton of preparation. This piece, which is wrote for HTO's special HIMSS 2011 print version, advises non-technical clinical and medical personnel to ease into technology so it doesn't harm their patients.",
      publisher: "Healthcare Technology Online HIMSS 2011 Special Publication",
      url:
        "http://www.healthcaretechnologyonline.com/download.mvc/Easing-Into-Healthcare-Automation-0001"
    },
    {
      name:
        "Develop lightweight ancillary tools connected to electronic health records systems",
      publishedOn: "Dec 14, 2010",
      description:
        'The 2009 stimulus bill\'s HITECH Act offers money to physicians, hospitals, and multi-hospital systems if they become "meaningful users" of certified electronic health records (EHR) systems. In order to meet meaningful use rules for EHR systems, you will need to create your own architecture to support lightweight applications. This article describes how to add meaningful use and other business requirements as lightweight ancillary tools connected to your EHR system without adding risk to your existing environment.',
      publisher: "IBM developerWorks",
      url:
        "http://www.ibm.com/developerworks/industry/library/ind-ancilehr/index.html"
    },
    {
      name: "AMA Interview: Easing into technology: Alternatives to a full EMR",
      description:
        'AMA\'s "American Medical News" magazine interviewed me for their piece on EMRs. I suggested that even if a full-fledged system is financially out of reach for your practice, there are ways to "ease into" automation.',
      publisher: "AMA Medical News",
      url: "http://www.ama-assn.org/amednews/2009/02/02/bisa0202.htm"
    },
    {
      name: "TYING IT ALL TOGETHER TO DELIVER IMPROVED POPULATION HEALTH",
      publishedOn: "May 2015",
      description:
        "To achieve system wide integration that enables population health management and realize the full potential of value based care coordinated and effective clinician communication is essential.  In this session experts discuss how to:  Identify the gaps and create linkages between disparate systems Bridge the care gap and provide real time collaboration that connects providers and real-time patient information Use technologies that support connectivity and communication between providers to enable value-based care",
      publisher: "Purpose Event",
      url:
        "http://purposeevents.com/sessions/tying-it-all-together-to-deliver-improved-population-health/"
    }
  ],
  recommendationsGiven: [
    {
      firstName: "Tim",
      lastName: "Histalk",
      company: "HIStalk",
      jobTitle: "Owner",
      text:
        "Like Tim, I'm a health IT blogger and I read HIStalk because the writing is prescient, accurate, useful, and relevant. Getting healthcare technology content right and keeping it readable is really tough but somehow Tim makes it look so easy. As a fellow blogger I've often read articles on HIStalk which makes me say \"gosh, I wish I wrote that!\" I've read Tim and his publications from day 1, will continue to read them on my own, and will continue to recommend them highly to everyone else who wants intelligible advice on healthcare technology. ",
      creationDate: "6/23/16, 12:01 PM"
    },
    {
      firstName: "Stephen",
      lastName: "Passalacqua",
      company: "Care Logistics - (a Jackson Healthcare Company)",
      jobTitle: "Senior Vice President, Client Growth & Development",
      text:
        "As simplifyMD, a SaaS based EHR, moved from its seed startup to venture funded growth and scale phases we asked Stephen to lead us as our COO. His command of operations leadership skills has all the strengths of precision when required but with enough agility to make sure a modern SaaS based software platform like ours could succeed. He came in and systematized our delivery process, regularized customer acquisition steps, formalized our services, deepened our support team, and basically did everything that goes into making a software company successful. If you need a senior leader with significant health IT skills that knows how to get things done, Stephen's your man. ",
      creationDate: "11/12/14, 7:51 AM"
    },
    {
      firstName: "Susan",
      lastName: "Beecham",
      company: "ChronicCareIQ",
      jobTitle: "Product Manager-Workflow Specialist",
      text:
        "Susan is one of those rare individuals in business that just loves working with customers, especially physician offices and their staff. She was a big reason for the early success of simplifyMD and Susan was one of the main the reasons why customers loved the company. Susan's leadership on the product design, customer support, and especially training teams priceless.",
      creationDate: "10/14/13, 3:30 PM"
    },
    {
      firstName: "Jessie",
      lastName: "Hoff",
      company: "athenahealth",
      jobTitle: "Director Integration Services",
      text:
        "Jessie is a terrific detailed-oriented manager who helped grow our electronic health records (EHR) startup. Launching and operating a technology company in the healthcare space is difficult because it requires tech skills, regulatory skills, HR skills, and patient-facing skills that aren't common in other industries. Jessie deftly navigated some precarious waters in our early days and helped operate our company with a mixture of competence, passion, and communications skills that were crucial in meeting many of our early milestones. If you're looking for someone to get the job done with a minimum of fuss and excellent skill set you can't go wrong with Jessie!",
      creationDate: "6/10/13, 3:06 AM"
    },
    {
      firstName: "Ayush",
      lastName: "Joshi",
      company: "Axis Bank",
      jobTitle: "DVP FASTag Axis Bank",
      text:
        "Ayush managed the outsourced group we hire to build a sophisticated medical document management system and electronic health record software. He did a great job leading the team from ideation and design to a production-ready system. His leadership was key to our successful release.",
      creationDate: "11/24/12, 8:08 AM"
    },
    {
      firstName: "Geo",
      lastName: "V.L",
      company: "Citrus Informatics (India) Pvt Ltd",
      jobTitle: "Lead Software Engineer & Architect",
      text:
        "Geo is a terrific engineer that turned in working code on more than one occasion. His ability to understand requirements, turn those requirements into designs that he can communicate with the client and then turn into implementations is great. I recommend him for almost any software project.",
      creationDate: "10/21/12, 7:01 PM"
    },
    {
      firstName: "Aparna",
      lastName: "M K",
      company: "Citrus Informatics (India) Pvt Ltd",
      jobTitle: "Lead Software Engineer & Architect",
      text:
        "Aparna has been working on PHP, MySQL, JavaScript, HTML, and Drupal code for us for several years now and has done a terrific job. She understands her development role well and delivers working code on consistent, reliable, and timely basis.",
      creationDate: "10/8/12, 5:39 AM"
    },
    {
      firstName: "Munir",
      lastName: "Faridi",
      company: "GEICO",
      jobTitle: "Senior Software Engineer II (Application DBA)",
      text:
        "Munir was our first and one of our most successful hires at Physia, a healthcare IT startup. His eagerness to learn, ability to take direction well, and implement code that needed to be produced all enabled him to be a successful member of a fast-paced venture-backed startup (with pretty high demands). Munir would be a great member of almost any team, technical or otherwise. He's a hard worker and gets the job done.",
      creationDate: "9/29/11, 4:06 AM"
    },
    {
      firstName: "Blaine",
      lastName: "Warkentine MD MPH",
      company: "Parvizi Surgical Innovation",
      jobTitle: "Digital Technology ",
      text:
        "Blaine is a unique visionary that understands the healthcare market as a consumer, as a doctor, as an entrepreneur, and as a marketing / communications specialist. If you're you're looking to build innovative healthcare solutions in almost any space you owe it to talk with Blaine because he can size up what you're doing quickly and give you tons of implementable ideas from either the healthcare professional or consumer perspectives. I would recommend Blaine to any group that wants to build out their innovation strategies or looking to get a business-oriented doctor's viewpoint about their offerings. When you need to understand where the healthcare market is heading or where solutions are needed, talk with Blaine.",
      creationDate: "5/31/11, 8:05 AM"
    },
    {
      firstName: "Blaine",
      lastName: "Warkentine MD MPH",
      company: "Parvizi Surgical Innovation",
      jobTitle: "Digital Technology ",
      text:
        "Blaine is a rare individual who has the education background of an MD and MBA but is even more rare because he's specifically focused on how to create innovative products and services within healthcare. He has more technology innovation ideas within a month than I've seen others produce in a lifetime. Because he understands doctors, patients, the business of healthcare, and the entire ecosystem of healthcare delivery, his thinking is often beyond most people to initially grasp; however, Blaine's ability to take his concepts and illustrate them and explain them to business customers allows him to make his case and take concepts forward. If you're looking for someone who understands healthcare, web 2.0, med tech, and product design you'll want Blaine either leading or on your team. You won't find a more impressive evangelist for your ideas.",
      creationDate: "2/27/11, 5:27 AM"
    },
    {
      firstName: "Raju",
      lastName: "Chauhan",
      company: "Immunicom, Inc.",
      jobTitle: "Vice President, Program Management",
      text:
        "Raju and I worked together while was a CTO; whenever I needed someone who could take basic business requirements and turn them into practical and precise data models and databases that would meet those requirements, I turned to Raju. His deep experience in the technology and ability to model database was a great start but it was his ability to focus on the business and the customers instead of bits and bytes that really set him apart. I found it a joy to work with him and would do so again in a heartbeat.",
      creationDate: "2/17/11, 6:22 AM"
    },
    {
      firstName: "Gregory",
      lastName: "Frey",
      company: "Jade Gong & Associates LLC",
      jobTitle: "Chief Operating Officer",
      text:
        "Greg is one of those rare individuals who understands IT but can also directly align it to financial and business goals instead of just looking at the technology. Greg cuts through IT hype and is able to understand deeper financial and performance metrics and how IT can either really help achieve those metrics or might hinder that goal. Greg's a no-nonsense guy and very good at problem solving because he focuses on results and not tactics.",
      creationDate: "2/16/11, 4:24 AM"
    },
    {
      firstName: "Mattie",
      lastName: "Case",
      company: "BD",
      jobTitle:
        "Exec Admin Assistant to WWVP/GM Dispensing Procedural Solutions",
      text:
        "As a senior executive I have both used and been around a number of executive admins and I must say that Mattie is a cut above. Mattie makes you look smarter, be better organized, and take care of the problems that you're likely to ignore far too long on your own. I can't remember a single task that was assigned to her that that wasn't completed on time and with a smile on her face; she fills in the gaps that you didn't even know you had.",
      creationDate: "9/1/10, 10:08 PM"
    },
    {
      firstName: "Prof. Rajendra",
      lastName: "Pratap Gupta",
      company: "United Nations",
      jobTitle:
        "Chair - Dynamic Coalition on 'Internet & Jobs' - Internet Governance Forum",
      text:
        "Rajendra and I only met a short time ago but in that time I've come to really admire his skills at putting healthcare technology issues into the right perspective: that's it about how that tech is put to use to save lives, improve care, or reduce costs. So many people are focused around health tech and IT today but very few people are like Rajendra -- he gets it. He understands that mHealth and mobile technologies can really make a difference if applied properly. I'm looking forward to working with him to solve real healthcare problems using the best mobile and health IT tools available.",
      creationDate: "5/20/10, 6:39 AM"
    },
    {
      firstName: "Dr. Steve",
      lastName: "Ambrose",
      company: "WALK THE RIDGE",
      jobTitle: "President",
      text:
        "Stephen's an innovative thinker who is looking outside the box and doing some really important work around subrogation and healthcare payments. His entrepreneurial instincts have led him to put together a stellar team of people around him to help him achieve his goal of doing nothing short of redefining the market around his offering. I love big thinkers and Stephen fits that category.",
      creationDate: "5/13/09, 8:11 PM"
    },
    {
      firstName: "Ayesha",
      lastName: "DeLorenzo",
      company: "Malfa Inc",
      jobTitle: "President and CFO",
      text:
        "Ayesha and I worked together while we were at Northrop Grumman's American Red Cross (ARC) National Biomedical Computer System (NBCS) project. She was in charge of communications and process management, both of which were very important in a regulated environment like ARC. The NBCS application suite is one of the world's largest FDA regulated 510k devices and Ayesha helped manage the CMMI Level 5 and FDA regulated software processes. She did a great job back then and I'd consider it a privilege to work with her again in the future. If you need a tech writer, a process manager, or a communications specialist you can't go wrong with Ayesha.",
      creationDate: "4/6/09, 4:20 AM"
    },
    {
      firstName: "Ryan",
      lastName: "Schutt",
      company: "Twin Technologies",
      jobTitle: "Senior Consultant",
      text:
        "Ryan's an excellent engineer and able to complete projects on time; he's done work for me on several projects and they have all gone well. Ryan's detail oriented, follows directions well, cares about the job he's doing, and his technical skills are broad and deep. I'd recommend him for almost any position where the delivery of high quality software is important.",
      creationDate: "2/17/09, 9:15 PM"
    },
    {
      firstName: "Alice",
      lastName: "Marshall",
      company: "Presto Vivace",
      jobTitle: "Founder and Owner",
      text:
        "Alice has a gift for writing and making complex concepts and technology very approachable and simple. I've recommended her to a number of colleagues and clients and will continue to do.",
      creationDate: "10/29/08, 9:26 PM"
    },
    {
      firstName: "Ujjwal",
      lastName: "Trivedi",
      company: "MoveInSync",
      jobTitle: "As. Director of Products",
      text:
        "Ujjwal's a solid engineer with good communications skill and excellent work ethic. He cares about what he does, always thinks the customer is right, and tries to do everything he can to solve problems (no matter how long it takes). He was able to learn new technologies quickly and is a good team player. I would work with him again anytime because he's honest and trustworthy.",
      creationDate: "8/3/08, 8:25 PM"
    },
    {
      firstName: "M.R.",
      lastName: "Jahanbin",
      company: "Jefferies",
      jobTitle: "Risk Quant Consultant",
      text:
        "Mohammad and I worked together at Maple Securities where he was head of Research and Development; he has the traits of that all excellent tech managers share: he cares about what he does, he puts business needs ahead of technology requirements, and he works well with people. I would work with him again at any time and I would wholeheartedly recommend him for any position where technology strategy is required to achieve business goals. Mohammad and I only worked together for less than two years but I learned a great deal from him and saw how a good R&D manager puts people first to achieve important business goals.",
      creationDate: "2/23/08, 5:24 AM"
    },
    {
      firstName: "Nainil",
      lastName: "Chheda",
      company: "Marketing Expert LLC",
      jobTitle: "CEO",
      text:
        "I've been in healthcare IT for years (I even blog about it http://www.healthcareguy.com). Nainil is one of the young bright stars of the health IT world and his ideas are both practical and quite useful. I recommend working with him on pretty much anything that has to do with medicine, especially medical technology. He and I worked together on a few articles and it was clear he knew his subject matter.",
      creationDate: "2/23/08, 5:20 AM"
    },
    {
      firstName: "Dov",
      lastName: "Levy",
      company: "Dovel Technologies",
      jobTitle: "co-founder and Chief Technologist",
      text:
        "I worked for Dov when he led the technology strategy, design, and implementation of the American Red Cross National Biomedical Computer System (NBCS) project in the late 90's. It was a very large and complex project and I was constantly amazed by Dov's ability to lead both business strategy and technology deployment. I learned many lessons from Dov, including how to put the users first, making sure technology decisions have direct business benefits, and how to lead a large team to deliver a nation-wide system by thinking through problems in small chunks. If I ever have a chance to work for him again, I'd do it in a heartbeat.",
      creationDate: "1/5/08, 2:16 AM"
    },
    {
      firstName: "Alexander",
      lastName: "Ginzburg",
      company: "Philips",
      jobTitle:
        "Senior Director, Software Architecture, Connected Care Innovation",
      text:
        "Alex is probably one of the most organized and focused engineering managers I've ever worked with; he's sure of what he wants, plans accordingly, and gets the job done. When I worked in his team it was a pleasure since he's not only technically knowledgeable, he's also business focused and client centric so the solutions he creates are usually on the mark.",
      creationDate: "4/19/07, 9:24 PM"
    },
    {
      firstName: "Amir",
      lastName: "Shah",
      company: "Uber Advanced Technologies Group",
      jobTitle: "Sr Engineering Manager",
      text:
        "Amir has worked for me in my capacity as CEO of Netspective and Chairman of the IEEE Computer Society Northern Virginia Chapter. He performed work such as website creation, installing a blog, doing database updates, and related IT Consulting and we had great results. He knows what he's doing and he works well with our folks. He's inexpensive as well.",
      creationDate: "1/18/07, 7:15 PM"
    },
    {
      firstName: "Pete",
      lastName: "Gambino",
      company: "Delaero, Inc.",
      jobTitle: "Owner",
      text:
        "I needed someone on short notice that could take over an entire .NET development effort and Pete's expertise in architecture, design, development, and management was exactly what I needed. His attention to detail, ability to communicate with the clients, and laser-like focus on results allowed us to meet client expecations each time. If you're looking for a disciplined leader with both business savvy and technical expertise you can't go wrong picking Peter.",
      creationDate: "1/8/07, 7:21 PM"
    },
    {
      firstName: "Suvajit",
      lastName: "Gupta",
      company: "Appian Corporation",
      jobTitle: "Executive Vice President Of Engineering",
      text:
        "If you need a project completed on schedule, Suvajit's your man. I've known Suvajit for almost 5 years and in that time I've come to consider his knowledge of software engineering processes to be without peer. He's come up with his own process model (called SPEED) and has the steps down to (almost) a science. I'd highly recommend him to anyone looking for software engineering leadership.",
      creationDate: "1/5/07, 11:41 PM"
    },
    {
      firstName: "Shahbaz",
      lastName: "Javeed",
      company: "Bloomberg LP",
      jobTitle: "Sr. Software Engineer",
      text:
        "When Shahbaz joined the team at Physia it gave us a jolt of engineering energy. He was able to solve some very difficult problems in our distributed computing infrastructure, rich client coding, and sys admin tasks. We were a small ASP with large ASP issues dealing with a complex healthcare environment and Shahbaz was instrumental to our success. I'd work with him again in a heartbeat.",
      creationDate: "9/15/05, 3:28 AM"
    },
    {
      firstName: "Matin",
      lastName: "Moosa",
      company: "Mussani and Company LP",
      jobTitle: "Owner",
      text:
        '"Smart", "Talented", and "Dedicated" are three words to describe Matin. Having known Matin for over 15 years I can highly recommend him for almost any position that requires things to get done. His dedication to his projects and personnel are without peer; he helped organize business development at my firm and we couldn\'t have done it that well without him.',
      creationDate: "4/9/05, 1:53 AM"
    },
    {
      firstName: "Andrew",
      lastName: "Glover",
      company: "Netflix",
      jobTitle: "Director, Productivity Engineering",
      text:
        "Quality is something that software industry is finally talking  about seriously and Andy's knowledge in that area is formidable. As a client, I'm very happy with his work and would recommend him highly to anyone looking to solve their software quality problems. Since he understands your business and your technology concerns, he's able to get things done quickly and with a minimum of fuss.",
      creationDate: "4/9/05, 1:50 AM"
    },
    {
      firstName: "Scott",
      lastName: "Sobel",
      company: "Emerald Star Software Inc.",
      jobTitle: "Owner",
      text:
        "When you need someone to make things happen, Scott's your man.  Having worked with Scott for almost 10 years, I've found his signular dedication to the client and his tireless efforts in support of his projects and personnel to be without peer. If you need a great technical well versed in database management or a executive-level project manager, you can't go wrong with Scott.",
      creationDate: "4/9/05, 1:42 AM"
    },
    {
      firstName: "Tom",
      lastName: "Figueroa",
      company: "JM Search",
      jobTitle: "Partner",
      text:
        "Tom and I spent some time together working on his client's recruiting requirement and I found him to be unusually dedicated to his client. Unlike most recruiters, he wasn't just looking to fill a position but instead acted as if he was part of the client's organization and doing what would be best for them. I highly recommend working with him.",
      creationDate: "4/9/05, 1:23 AM"
    },
    {
      firstName: "michael",
      lastName: "fitzmaurice",
      company: "Fitzmaurice and Company",
      jobTitle: "Investor",
      text:
        "Mike is one of those rare folks in business development circles that truly understands both the business use of technology and the underpinnings that make a technology successful in practice.I continue to be very impressed with his capabilities and his ability to rally technical and non-technical people around Linux Clusters and other open source solutions to common business problems.",
      creationDate: "1/11/05, 5:18 AM"
    },
    {
      firstName: "Terry",
      lastName: "Zagar",
      company: "Terry Zagar",
      jobTitle: "Sole Proprietor",
      text:
        "Terry is a very bright and exceptionally astute technologist and architect. He understands both the business and technology ramifications of all enterprise architecture decisions. I'd strong recommend working with him for almost any project.",
      creationDate: "3/10/04, 12:17 AM"
    },
    {
      firstName: "Jay",
      lastName: "Zimmerman",
      company: "NFJSOne",
      jobTitle: "President",
      text:
        "Jay puts together one of the finest conferences on Java and Open Source technologies that any developer can attend. His ability to put together some great minds to help train savvy or junior developers on the most common tools and techniques is truly remarkable. I highly recommend his conferences and his company. You can't go wrong working with Jay.",
      creationDate: "2/25/04, 7:35 AM"
    },
    {
      firstName: "Joe",
      lastName: "Walsh",
      company: "New Urbana",
      jobTitle: "Advisor",
      text:
        "Joe's tireless efforts to enhance entreprenurship in our area is to be commended. I've been to many events that he's hosted or otherwise setup and they've all been useful for us as a technology startup. I'd highly recommend working with him in almost any capacity. If you need help growing your business, he's the man to see.",
      creationDate: "2/22/04, 11:24 PM"
    },
    {
      firstName: "David",
      lastName: "Frankil",
      company: "CrossState Credit Union Association Solutions Corp.",
      jobTitle: "President",
      text:
        "David's one of those people that are able to just get things done. His advice for our technology firm was always sound and his business contacts are plentiful. I'd recommend working with him for almost any business development activity.",
      creationDate: "2/18/04, 8:17 AM"
    },
    {
      firstName: "Sada",
      lastName: "Rajagopalan",
      company: "Asurion",
      jobTitle: "Vice President - Enterprise Architecture and Platforms",
      text:
        "Having seen Sada in action I must say he's one of the most impressive engineers I've worked with. His breadth of Enterprise Architecture knowledge, coupled with his ability to implement complex systems by coding the solutions himself when necessary, is truly unique. If you need an architect or senior engineer to do almost any software project you can't go wrong with Sada.",
      creationDate: "2/18/04, 8:13 AM"
    },
    {
      firstName: "Lisa",
      lastName: "Spory",
      company: "Sevatec, Inc.",
      jobTitle: "Vice President",
      text:
        "Lisa's a very bright and engaging engineer. She's one of those rare programmers that care more about the customer and what solution she's creating for them than with the tools and technology is being used. Her communications skills are also outstanding. I'd recommend her for almost any position where building a high-quality product and keeping a customer happy are important.",
      creationDate: "2/17/04, 9:46 PM"
    },
    {
      firstName: "Tom",
      lastName: "Russotto",
      company: "SM&A",
      jobTitle: "Associate",
      text:
        "Tom's one of those rare individuals who can truly do it all: he teaches, he can dabble in code, he understands enterprise architecture, he understands business and how IT can provide value, and he knows how to close deals. If you need someone with a wide variety of experience and expertise you can't go wrong with Tom.",
      creationDate: "2/17/04, 5:49 AM"
    },
    {
      firstName: "Mohammad",
      lastName: "Rahman",
      company: "Rahman LLC",
      jobTitle: "Managing Attorney",
      text:
        "Mohammad prepared a patent application for me and my firm and he did a terrific job. With very little time spent on my part he was able to understand my invention and work the application through to completion. I'd recommend using Mohammad for almost any IP legal work but especially for creating patents.",
      creationDate: "2/17/04, 1:39 AM"
    },
    {
      firstName: "Clark",
      lastName: "Richey",
      company: "FactGem",
      jobTitle: "Chief Technology Officer",
      text:
        "Clark has been a beacon of Java knowledge for all the members of Juggacino. His tireless efforts have led to an increase in membership and attracted many top-notch speakers. I would recommend Clark in almost any software development capacity.",
      creationDate: "2/17/04, 1:36 AM"
    },
    {
      firstName: "Tom",
      lastName: "Woteki",
      company: "Virginia Tech",
      jobTitle: "Professor of Practice, Statistics",
      text:
        "I worked under Tom for many years and have found it both rewarding and educational. He is very personable and his technical knowledge is formidable but his ability to take technology and apply them to business solutions is what I admired most. I strongly recommend working with him in almost any capacity.",
      creationDate: "2/16/04, 9:54 PM"
    },
    {
      firstName: "Zia",
      lastName: "Rahman",
      company: "Intelliinfotek LLC",
      jobTitle: "Owner",
      text:
        "Zia is a great engineer and is dedicated to customer satisfaction in all areas of software development. His technical skills are matched by his business acumen and those two combined attributes lead him to complete software projects on time and end with happy customers.",
      creationDate: "2/16/04, 12:20 PM"
    },
    {
      firstName: "Ahmad",
      lastName: "Mian",
      company: "FileControl Partners",
      jobTitle: "President",
      text:
        "When you need something done, look no further than Ahmad. He happens to be one of the most well-connected people I know and is one of those rare individuals that says what he means and does what he says. I would highly recommend working with him in almost any endeavor.",
      creationDate: "2/16/04, 12:18 PM"
    },
    {
      firstName: "Kamesh",
      lastName: "Pemmaraju",
      company: "Platform9 Systems",
      jobTitle: "Head Of Product Marketing",
      text:
        "When you need a leader for your project, look no further than Kamesh. His attention to detail, his business acumen, and his focus on customer satisfaction makes him a perfect project manager. I would highly recommend him for almost any project.",
      creationDate: "2/16/04, 10:02 AM"
    },
    {
      firstName: "Mike",
      lastName: "Kitchener",
      company: "Ignite IT",
      jobTitle: "Project & Release Manager/Scrum Master",
      text:
        "Mike is a rare commodity in the systems analysis business: he genuinely cares about his customers. As a business analyst I would recommend him to anyone trying to build large or small software applications where they need someone to either lead the project or handhold the customer through an implementation.",
      creationDate: "2/16/04, 6:31 AM"
    },
    {
      firstName: "Lloyd",
      lastName: "Brodsky",
      company: "Optum",
      jobTitle:
        "Pre-sales Solution Architect and Analytical Process Consultant",
      text:
        "With Lloyd's excellent background in healthcare informatics we were able to get a healthcare software application up and running in under 12 months. He has excellent communications skills and his great project management skills allowed him to complete tasks on-time and on-budget.",
      creationDate: "2/16/04, 6:09 AM"
    },
    {
      firstName: "Denys",
      lastName: "Kim",
      company: "American Red Cross",
      jobTitle: "Lead Enterprise Architect",
      text:
        "I highly recommend Denys as an enterprise architect and Java/J2EE senior engineer. He has great architecture knowledge to help specify systems and backs that up with a depth of programming understanding required to implement systems as well. He has excellent business skills and his technical capabilities become sharper because he knows how to apply technology to solve business problems.",
      creationDate: "2/16/04, 5:55 AM"
    },
    {
      firstName: "J. David",
      lastName: "Harvey",
      company: "LawVision LLC",
      jobTitle: "Senior Consultant",
      text:
        "David's well connected in the Mid-Atlantic venture community and I'd highly recommend using him if you have any need for capital, business planning, or general business advice. He's been helping me and my firm for many years and I've been very happy with the services and advice he's provided.",
      creationDate: "2/15/04, 10:26 PM"
    },
    {
      firstName: "Aye",
      lastName: "Thu",
      company: "Dialogue",
      jobTitle: "Founder",
      text:
        "Aye is a very bright and intelligent engineer who really cares about the work that he performs. I would highly recommend him for any technology work or software development project. He's got excellent programming skills and can interface with customers, too.",
      creationDate: "2/15/04, 9:18 PM"
    }
  ],
  recommendationsReceived: [
    {
      firstName: "Tolga U.",
      lastName: "Ural, MBA",
      company: "Clinical Referral Directories and Imagine Media Partners",
      jobTitle: "Founder & CEO",
      text:
        "I had the pleasure of attending Shahid's social media webinar and found it to be very informative, full of great tips for next month's HIMMS. His direct style really makes you take a good look at where you stand to improve your messaging and how best to prioritize solving the customer's problems and see things from their perspective.",
      creationDate: "1/16/14, 12:03 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Manoj",
      lastName: "Vadavat",
      company: "Collinear Healthcare Consultants pvt ltd",
      jobTitle: "CEO",
      text:
        "Shahid's blogs is a must read for any Healthcare, IT and Healthcare IT person. I am already asking my collegues and interns to follow this on a daily basis. This is the best you can get    Regards,    Manoj Vadavat  COO  Collinear Technology Solutions",
      creationDate: "11/18/09, 3:15 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Jeff",
      lastName: "Lamkin",
      company: "One Water Marine Holdings",
      jobTitle: "Member Board of Directors",
      text:
        "Shahid is a man you can count on!  When times get tough and you look around to see who will fight the fight with you, Shahid will be by your side.  He is self motivated, extremely smart and capable of getting it done.  He is a superb manager and also willing to roll up his sleeves to do it himself when that is the best solution.  We can all learn a few things from Shahid!",
      creationDate: "11/30/13, 7:44 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Ayesha",
      lastName: "DeLorenzo",
      company: "Malfa Inc",
      jobTitle: "President and CFO",
      text:
        "Shahid\u0092s dynamic and energetic leadership was key to the success of the FDA regulated program. His continued interest in process improvement led to many changes that enhanced techniques on this large program. Shahid\u0092s innovative management styles were incorporated at all levels of the program and later used on several other programs.",
      creationDate: "6/3/04, 2:33 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Eddie",
      lastName: "Garcia",
      company: "Accenture",
      jobTitle: "Technology Innovation Senior Manager",
      text:
        "I met Shahid at the Dell Think Tank on Healthcare earlier this year. He was very knowledgeable about the economics behind HITECH and the widespread adoption of EMR technology, and how these fit within the regulatory framework. He obviously has a great deal of experience in the industry, and provides thought leadership. I look forward to working with Shahid in future projects and/or initiatives.",
      creationDate: "5/9/13, 10:09 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Alexander",
      lastName: "Rosenthal",
      company: "National Institutes of Health",
      jobTitle:
        "Chief Technology Officer, National Institute of Allergy and Infectious Diseases",
      text:
        "Shahid provided me with valuable advice in establishing a global database for supporting clinical trials. His deep understanding of the subject area and high integrity left a deep mark on the project.",
      creationDate: "8/2/09, 7:17 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Lloyd",
      lastName: "Brodsky",
      company: "Optum",
      jobTitle:
        "Pre-sales Solution Architect and Analytical Process Consultant",
      text:
        "Shahid is a creative and extremely competent technical architect. Several people, myself included, were inspired to join the company by the vision expressed in his design.",
      creationDate: "2/18/04, 6:19 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Adam",
      lastName: "Gentry",
      company: "Linden Advisors",
      jobTitle: "Director Of Information Technology",
      text:
        "Shahid was hired by our company as a consultant to establish fundamental changes in how we develop. His insight into Design Patterns, Testing, Refactoring, Project Management and his grasp of advanced programming came together on a large project. If not for his guidance, this project of ours would not have been able to meet the deadlines set for us.",
      creationDate: "1/25/13, 9:25 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Ayush",
      lastName: "Joshi",
      company: "Axis Bank",
      jobTitle: "DVP FASTag Axis Bank",
      text:
        "I worked with Shahid for almost one and half year, and found him truly inspirational when it comes to guiding and mentoring a raw team.It was  amazing to found him so profound in all technical areas, he guided us in almost all areas with his rich technical and business thoughts, I must say one of his key managerial strength is his ability to easily zooms in and out on any small to big issues in no time. I admire his technique where he leveraged his technical strengths to get maximum issues resolved on no time on our daily calls and motivated us to get the best out of us.I definitely look forward to have an association with him again.",
      creationDate: "1/25/09, 1:41 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Breaux",
      lastName: "Castleman",
      company: "Advanced Micro Instruments, Inc.",
      jobTitle: "Director",
      text:
        "He demonstrated competence and brilliance in the  development of a unique software.  He conceived an innovative solution to a fundamental industry problem, and worked collaboratively with healthcare experts in the development of applications. As a thinker, engineer, leader, manager, and committed employee I recommend Mr. Shah without reservation. His ethical standards are of the highest order.",
      creationDate: "2/17/04, 10:36 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Blaine",
      lastName: "Warkentine MD MPH",
      company: "Parvizi Surgical Innovation",
      jobTitle: "Digital Technology ",
      text:
        "Shahid is supremely talented in all aspects of business, marketing, start ups, health IT, platforms, frameworks, architecture, and so much more he constantly astounds me. But what makes him really stand out is his ability to sift through your needs and simplify everything.  Ultra pragmatic and never burdened with a hidden agenda He is very unique and highly recommended.",
      creationDate: "2/27/11, 5:38 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Alice",
      lastName: "Marshall",
      company: "Presto Vivace",
      jobTitle: "Founder and Owner",
      text:
        "I had the honor of working for the International Association of Software Architects, of which Shahid Shah is a member of the Board. Shah is one of those people who know how to make things happen.",
      creationDate: "10/29/08, 8:43 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Sayed",
      lastName: "Yousuf",
      company: "WorkForce Software",
      jobTitle: "Software Development Manager",
      text:
        "I had started working with Shahid on this Health Care project since June 1999. It was really a pleasure working with Physia's team, specially with Shahid. I had gained a tremenduous knowledge about developing an Internet ASP application from him. He has a complete command and knowledge of what he develops. He is a mentor and a great person. I would highly recommend working with him.",
      creationDate: "2/16/04, 9:38 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Prof. Rajendra",
      lastName: "Pratap Gupta",
      company: "United Nations",
      jobTitle:
        "Chair - Dynamic Coalition on 'Internet & Jobs' - Internet Governance Forum",
      text:
        "Shahid is a rare leader in Technology . I and my friends consult him on important issues related to technology, and he has instant answers ! His blog www.healthcareguy.com is highly recommended for people into HIT. His knowledge about the IT domain is vast and is quite helpful to people who will get confused with the vendors driven IT industry .     Above all, Shahid is not driven for money and he is always willing to offer his expertise when needed . A great human being !!",
      creationDate: "5/21/10, 2:02 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Ujjwal",
      lastName: "Trivedi",
      company: "MoveInSync",
      jobTitle: "As. Director of Products",
      text:
        "Shahid is an exceptional leader, a very positive person, detail oriented manager and a programmer at heart. He is great at communication and persuation. Above everything he is a very kind hearted and admirable person. A big part of what I am today is due to inspiration and constant mentoring from Shahid. My 14 months of association with him has been a period of great learning and development. I just wish I get to work with him again in future. This recommendation is a small token of gratitude towards him.",
      creationDate: "8/3/08, 5:30 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Dr. Steve",
      lastName: "Ambrose",
      company: "WALK THE RIDGE",
      jobTitle: "President",
      text:
        "When I talk about Shahid several things come to immediate thought.      He consistently overdelivers, is a plethora of useful expertise and information, has shown himself to be an advocate and champion of both technology and innovation and he is open and honest.  There is nothing more refreshing that working with someone who is not afraid to voice an opinion that is best for the company, not just what the executive wants to hear.      If 4 stars were the best rating...I'd have to give him 5.",
      creationDate: "5/12/09, 12:58 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Paul",
      lastName: "Baker",
      company: "Office of Management and Budget",
      jobTitle: "Director of Information Mgmt",
      text:
        'Shahid has a truly unique mix of technology expertise and business acumen.  He is gifted at taking complex processes and distilling them down to their essence for the purpose of re-engineering and automation.  He excels at every level of information engineering from the most conceptual and theoretical all the way down to bits and bytes.  He has a tireless energy and focus, and never rests until the customer is "thrilled" with the outcome.  His project management skills are state-of-the-art in terms of using agile methods and the most recent technologies, and yet he always matches the perfect mix of tools to the job at hand.  He is a true master-craftsman when it comes to coding, consistently staying current on emerging frameworks, languages, and technologies.  But, most importantly, he is extremely collegial and a joy to work with.  In fact, he is the rare type of guy who can exhaust my ability to come up with new superlatives, and that is no small feat.  I cannot recommend him highly enough.',
      creationDate: "4/15/08, 9:36 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Pete",
      lastName: "Gambino",
      company: "Delaero, Inc.",
      jobTitle: "Owner",
      text:
        "I've worked with Shahid on several different engagements and found him to be a highly motivated and insightful consultant.  His knowledge of the technical trends in the medical industry is unsurpassed.  Combine this with his technical design and team leadership qualities and Shahid was a key figure in leading our multi-functional team to success.",
      creationDate: "1/10/07, 2:40 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Pete",
      lastName: "Gambino",
      company: "Delaero, Inc.",
      jobTitle: "Owner",
      text:
        "I've worked with Shahid on several different engagements and found him to be a highly motivated and insightful consultant.  His knowledge of the technical trends in the medical industry is unsurpassed.  Combine this with his technical design and team leadership qualities and Shahid was a key figure in leading our multi-functional to success.",
      creationDate: "1/9/07, 12:07 PM",
      status: "REPLACED"
    },
    {
      firstName: "Shahbaz",
      lastName: "Javeed",
      company: "Bloomberg LP",
      jobTitle: "Sr. Software Engineer",
      text:
        "I worked with Shahid on multiple projects in the healthcare industry as well as on the SparX J2EE framework.  He is, by far, the most creative, energetic, and technically savvy person I have ever worked with.",
      creationDate: "9/6/05, 12:35 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Tom",
      lastName: "Figueroa",
      company: "JM Search",
      jobTitle: "Partner",
      text:
        "Shahid possesses a unique blend of technical and leadership skills.  He has strong communication skills and was always very diligent at following up.  Any company that is lucky enough to retain his services won't be disappointed.",
      creationDate: "4/11/05, 5:54 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Andrew",
      lastName: "Glover",
      company: "Netflix",
      jobTitle: "Director, Productivity Engineering",
      text:
        "Shahid is a top notch technical guru and an adept entrepreneur guru who can effectively fuse technology with business concerns. There are few people who can communicate complex business and technical aspects as well as Shahid, and his professionalism is unmatched. I have an immense amount of trust and respect for Shahid and I would gladly offer him a referral.",
      creationDate: "4/10/05, 10:28 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Don",
      lastName: "Muldoon",
      company: "Sycamore Informatics",
      jobTitle: "Principal Architect",
      text:
        "The extent of Shahid\u0092s technical knowledge is overwhelming.  His communication and presentation style, from rank and file developers to executives, is effective, informed and professional.  He quickly assimilated our team into J2EE best practices and design patterns.  If your business requirements include enterprise class software design and development make Shahid part of your solution.",
      creationDate: "12/30/04, 10:14 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Sada",
      lastName: "Rajagopalan",
      company: "Asurion",
      jobTitle: "Vice President - Enterprise Architecture and Platforms",
      text:
        "Shahid is a thought leader in creating J2EE frameworks for development projects has the knowledge in J2EE platform combined with strong organizational skills making him a strong asset.I enjoy working with Shahid for the energy and enthusiasm he brings to the team. It will be a pleasure to work with him in future as there are few people who has his drive, energy and passion about what he does.",
      creationDate: "12/30/04, 1:53 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Jon",
      lastName: "Strande",
      company: "AstraZeneca",
      jobTitle: "Head of Design, Digital Health",
      text:
        "I had the opportunity to review some of Shahids work with Netspective and I was VERY impressed. I always enjoy meeting people who have the ability to see the big picture and the talent to use that knowledge to deliver useful solutions.",
      creationDate: "3/9/04, 1:58 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Kamesh",
      lastName: "Pemmaraju",
      company: "Platform9 Systems",
      jobTitle: "Head Of Product Marketing",
      text:
        "If you are looking for a deep technology expert with a clear understanding of customer business needs, look no further than Shahid. Shahid bring a phenomenal understanding of software architecture and design to the table, not merely from a theoretical point of view but from a practical hands-on perspective as well, having implemented many software projects from the ground-up.",
      creationDate: "2/18/04, 10:57 PM",
      status: "VISIBLE"
    },
    {
      firstName: "David",
      lastName: "Frankil",
      company: "CrossState Credit Union Association Solutions Corp.",
      jobTitle: "President",
      text:
        "Savvy, results oriented, keen to understand your strategic needs and capable of understanding a bigger picture -- what else do you want in someone designing and building software?  Every time we have used Shahid and Sparx/Netspective in client engagements the result has always been predictable -- outstanding, which means a satisfied client. Highest recommendation!",
      creationDate: "2/18/04, 10:20 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Lisa",
      lastName: "Spory",
      company: "Sevatec, Inc.",
      jobTitle: "Vice President",
      text:
        "I worked closely with Shahid during our initial evaluation of the Sparx Application Platform\u0099, and more recently during our first implementation using Sparx.  I am confident that using Sparx on our program will help us to deliver better products faster, not only because of the quality of the framework itself, but also due to the responsiveness and involvement of Shahid as his team.",
      creationDate: "2/17/04, 9:15 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Tom",
      lastName: "Russotto",
      company: "SM&A",
      jobTitle: "Associate",
      text:
        "Shahid is one of the brightest individuals that I have ever meet.  He not only understands information technology but he genuinely wants to help his customers.  Shahid is a tireless worker and an honest and ethical person.",
      creationDate: "2/17/04, 3:39 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Clark",
      lastName: "Richey",
      company: "FactGem",
      jobTitle: "Chief Technology Officer",
      text:
        "Shahid has proven himself to be a true technology innovator. He is a true professional who is always willing to take the time to help educate others. I would stringly recommend Shahid for any technology leadership role.",
      creationDate: "2/17/04, 2:28 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Lalit",
      lastName: "Parashar",
      company: "Maple Securities",
      jobTitle: "Programmer",
      text:
        "Shahid has been training us on advanced software engineering (OOP) and test-driven development techniques on a new Loan Processing System my firm is building.   It has been a great working with him while he has been mentoring our team. He knows his way around tools and technologies and is able to teach programmers how to use them.",
      creationDate: "2/17/04, 1:07 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Zia",
      lastName: "Rahman",
      company: "Intelliinfotek LLC",
      jobTitle: "Owner",
      text:
        "I have worked with Shahid on very time sensitve project for Verizon Wireless and Shahid's work was extremely professional and tech support was excellent.",
      creationDate: "2/16/04, 1:57 PM",
      status: "VISIBLE"
    },
    {
      firstName: "Aye",
      lastName: "Thu",
      company: "Dialogue",
      jobTitle: "Founder",
      text:
        "I've worked with Shahid on different projects and he's always impressed me with his knowledge of all the latest technologies. His knowledge and experience with software architecture and design have helped tremendously in building quality products. Also the leadership and synergy that he brings to a team is very outstanding. He would be a great asset to any project or team.",
      creationDate: "2/16/04, 11:31 AM",
      status: "VISIBLE"
    },
    {
      firstName: "Denys",
      lastName: "Kim",
      company: "American Red Cross",
      jobTitle: "Lead Enterprise Architect",
      text:
        "I have been extremely impressed with Shahid as an entreprenuer and a technologist.  His breath of knowledge on every aspect of IT as well as vertical expertise is certainly one of his most impressive attributes. He also possesses the business acument to bridge the gap between technology and business to ensure that the correct IT solution is applied to address key business drivers.",
      creationDate: "2/16/04, 10:19 AM",
      status: "VISIBLE"
    },
    {
      firstName: "James",
      lastName: "Ogura",
      company: "The College Board",
      jobTitle: "Cloud Architect",
      text:
        "Shahid is a very impressive individual.  He is constantly update-to-date with the latest technologies.  This coupled with the ability to articulate his ideas clearly makes him a rare individual.  I would highly recommend working with Shahid.",
      creationDate: "2/13/04, 3:43 AM",
      status: "VISIBLE"
    }
  ],
  skills: [
    { name: "Investment Advisory" },
    { name: "Engaging Public Speaker" },
    { name: "Entrepreneur" },
    { name: "Equity Research" },
    { name: "Valuation" },
    { name: "Board of Directors" },
    { name: "Medical Device R&D" },
    { name: "Healthcare Information Technology" },
    { name: "Enterprise Architecture" },
    { name: "Agile Methodologies" },
    { name: "Software Development" },
    { name: "Software Project Management" },
    { name: "IT Strategy" },
    { name: "Software Engineering" },
    { name: "Healthcare" },
    { name: "Product Management" },
    { name: "Integration" },
    { name: "Cloud Computing" },
    { name: "System Architecture" },
    { name: "Software Design" },
    { name: "Unix" },
    { name: "Security" },
    { name: "SDLC" },
    { name: "Business Intelligence" },
    { name: "Requirements Analysis" },
    { name: "Programming" },
    { name: "Java" },
    { name: "Mobile Applications" },
    { name: "SaaS" },
    { name: "Technology strategy development" },
    { name: "SQL" },
    { name: "SOA" },
    { name: "C++" },
    { name: "JavaScript" },
    { name: "Linux" },
    { name: "Operating Systems" },
    { name: "PHP" },
    { name: "C" },
    { name: "Technical Management" },
    { name: "Due Diligence" },
    { name: "Information Architecture" },
    { name: "Healthcare IT" },
    { name: "Relational databases" },
    { name: "Application Architecture" },
    { name: "Medical Informatics" },
    { name: "J2EE" },
    { name: "Agile" },
    { name: "Publisher" },
    { name: "Writer" },
    { name: "Software as a Service (SaaS)" }
  ]
};

export default linkedInArchive;
